export * from "./home/home";
export * from "./register/register";
export * from "./login/login";
export * from "./register_profile/register_profile";
export * from "./profile/profile";
export * from "./main/main";
export * from "./doctors/doctors"
export * from "./profileDoctors/profileDoctors"
export * from "./scheduling/scheduling"